//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int id { get; set; }
        public string name { get; set; }
        public decimal value { get; set; }
        public System.DateTime date { get; set; }
        public int account_id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
